package object

import "errors"

// Named errors defined by the GitForensics specification (§5, §6, §7).
var (
	// Envelope / Loose Object errors (§5)
	ErrInvalidZlibStream       = errors.New("invalid zlib stream")
	ErrTruncatedZlibStream     = errors.New("truncated zlib stream")
	ErrZlibChecksumFailed      = errors.New("zlib checksum failed")
	ErrMissingHeaderTerminator = errors.New("missing header terminator")
	ErrUnknownObjectType       = errors.New("unknown object type")
	ErrMalformedSize           = errors.New("malformed object size")
	ErrTruncatedPayload        = errors.New("truncated payload")
	ErrTrailingPayloadData     = errors.New("trailing payload data")
	ErrObjectTooLarge          = errors.New("object exceeds maximum allowed size")
	ErrInvalidOID              = errors.New("invalid object ID")

	// Tree parsing errors (§6)
	ErrTreeEntryMissingSeparator = errors.New("tree entry missing separator")
	ErrTruncatedTreeEntry        = errors.New("truncated tree entry")
	ErrTreeEntryMalformedMode    = errors.New("malformed tree entry mode")

	// Commit parsing errors (§7)
	ErrCommitMissingTree             = errors.New("commit missing tree header")
	ErrCommitMalformedTreeRef        = errors.New("commit malformed tree ref")
	ErrCommitMalformedParentRef      = errors.New("commit malformed parent ref")
	ErrCommitMissingAuthor           = errors.New("commit missing author")
	ErrCommitMissingCommitter        = errors.New("commit missing committer")
	ErrCommitDuplicateAuthor         = errors.New("commit duplicate author")
	ErrCommitDuplicateCommitter      = errors.New("commit duplicate committer")
	ErrCommitMalformedAuthorLine     = errors.New("commit malformed author line")
	ErrCommitMalformedCommitterLine  = errors.New("commit malformed committer line")
	ErrCommitMalformedTimestamp      = errors.New("commit malformed timestamp")
	ErrCommitMalformedTimezone       = errors.New("commit malformed timezone")
	ErrCommitMissingMessageSeparator = errors.New("commit missing message separator")
	ErrCommitMalformedHeaderLine     = errors.New("commit malformed header line")

	// Repository and Reference errors (§4)
	ErrRepositoryNotFound   = errors.New("git repository not found")
	ErrSymbolicRefCycle     = errors.New("symbolic ref cycle detected")
	ErrMaxPeelDepthExceeded = errors.New("maximum tag peel depth exceeded")
	ErrMaxTreeDepthExceeded = errors.New("maximum tree recursion depth exceeded")
	ErrObjectNotFound       = errors.New("object not found")

	// Packfile and Delta errors (§16, §17, §18)
	ErrNotAPackFile                    = errors.New("not a valid pack file")
	ErrUnsupportedPackVersion          = errors.New("unsupported pack version")
	ErrInvalidPackEntryType            = errors.New("invalid pack entry type")
	ErrPackEntrySizeTooLarge           = errors.New("pack entry size exceeds safety limit")
	ErrTruncatedPackEntry              = errors.New("truncated pack entry header")
	ErrPackObjectSizeMismatch          = errors.New("pack object inflated size mismatch")
	ErrTruncatedOfsDeltaOffset         = errors.New("truncated ofs delta offset")
	ErrInvalidOfsDeltaOffset           = errors.New("invalid ofs delta base offset")
	ErrDeltaBaseSizeMismatch           = errors.New("delta base size mismatch")
	ErrDeltaCopyOutOfBounds            = errors.New("delta copy instruction out of bounds")
	ErrInvalidDeltaInstruction         = errors.New("invalid delta instruction")
	ErrDeltaReconstructionSizeMismatch = errors.New("delta reconstruction size mismatch")
	ErrTruncatedDeltaInstruction       = errors.New("truncated delta instruction")
	ErrDeltaTrailingInstructionData    = errors.New("trailing delta instruction data")
	ErrDeltaChainCycleDetected         = errors.New("delta chain cycle detected")
	ErrPackChecksumMismatch            = errors.New("pack checksum mismatch")
	ErrPackCountMismatch               = errors.New("pack entry count mismatch")
	ErrPackTruncatedOrCorrupted        = errors.New("pack file truncated or corrupted")
	ErrMaxDeltaDepthExceeded           = errors.New("maximum delta chain depth exceeded")
	ErrUnsupportedRefDelta             = errors.New("unsupported ref delta")
)
